_base_:
- ../model/ispikformer.yml
- ../dataset/metr-la.yml
_custom_imports_:
- SeqSNN.network
- SeqSNN.dataset
- SeqSNN.runner

data:
  raw_label: False
  window: 168
  horizon: 48   # if horizen = 6, window = 12
  normalize: 3

runner:
  type: vsts
  batch_size: 32
  # batch_size: 64
  aggregate: False
  out_size: 96
  denormalize: True
  task: regression
  optimizer: Adam
  lr: 0.0001
  weight_decay: 0.0
  loss_fn: mse
  metrics: [r2, rrse]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 30
  valid_variates: 207

network:
  type: iSpikformer
  #dim: 64
  dim: 256
  d_ff: 1024
  # d_ff: 256
  depths: 2
  num_steps: 4
  heads: 8
  encoder_type: conv

runtime:
  seed: 42
  output_dir:  /home/feng/feng5/timeseries/outputs/iSpikformer_horizon=48_metr-la