_base_:
- ../model/ispikformer.yml
- ../dataset/pems-bay.yml
_custom_imports_:
- SeqSNN.network
- SeqSNN.dataset
- SeqSNN.runner

data:
  raw_label: False
  window: 168
  horizon: 48
  normalize: 2

runner:
  type: vsts
  batch_size: 32
  aggregate: False
  out_size: 48
  denormalize: True
  task: regression
  optimizer: Adam
  lr: 0.0005
  weight_decay: 0.0
  loss_fn: mse
  metrics: [r2, rrse]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 20
  valid_variates: 325

network:
  type: iSpikformer
  dim: 512
  d_ff: 2048
  depths: 1
  num_steps: 4
  heads: 8

runtime:
  seed: 40
  output_dir:  /home/feng/feng5/timeseries/outputs/ispikformer_horizon=48_pems-bay